#!/bin/bash

export NVARCH=`uname -s`_`uname -m`;

export NVCOMPILERS=/opt/nvidia/hpc_sdk;

export MANPATH=$MANPATH:$NVCOMPILERS/$NVARCH/21.7/compilers/man;

export PATH=$NVCOMPILERS/$NVARCH/21.7/compilers/bin:$PATH; 